AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Resources:
  SSLCertFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ssl_cert/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        SSLCert:
          Type: Api 
          Properties:
            Path: /site
            Method: get

Outputs:
  SSLCertApi:
    Description: "API Gateway endpoint URL for Prod stage for SSLCert function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ssl_cert/"
  SSLCertFunction:
    Description: "SSLCert Lambda Function ARN"
    Value: !GetAtt SSLCertFunction.Arn
  SSLCertFunctionIamRole:
    Description: "Implicit IAM Role created for SSLCert function"
    Value: !GetAtt SSLCertFunctionRole.Arn
